
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const Analytics = lazy(() => import("./pages/Analytics.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const CreateListing = lazy(() => import("./pages/CreateListing.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Inventory = lazy(() => import("./pages/Inventory.tsx"));
const Listing = lazy(() => import("./pages/Listing.tsx"));
const Listings = lazy(() => import("./pages/Listings.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const PriceAnalysis = lazy(() => import("./pages/PriceAnalysis.tsx"));
const Pricing = lazy(() => import("./pages/Pricing.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const Register = lazy(() => import("./pages/Register.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/analytics", element: <Analytics />},
	{ path: "/", element: <App />},
	{ path: "/create-listing", element: <CreateListing />},
	{ path: "/createlisting", element: <CreateListing />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/inventory", element: <Inventory />},
	{ path: "/listing", element: <Listing />},
	{ path: "/listings", element: <Listings />},
	{ path: "/login", element: <Login />},
	{ path: "/price-analysis", element: <PriceAnalysis />},
	{ path: "/priceanalysis", element: <PriceAnalysis />},
	{ path: "/pricing", element: <Pricing />},
	{ path: "/profile", element: <Profile />},
	{ path: "/register", element: <Register />},

];
